# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

after_success:
  - Rscript -e 'covr::codecov()'

addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base-dev
    - libcurl4-openssl-dev 
    - libxml2-dev
    - unixodbc-dev
    - r-recommended
    - pandoc
    
warnings_are_errors: false